# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    depends_on :
      - database
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - /srv/wiki/images:/var/www/html/images
      # uncomment after wiki setup
      #- /srv/wiki/LocalSettings.php:/var/www/html/LocalSettings.php 
  database:
    image: mariadb
    restart: always
    ports:
      - 3306:3306  
    volumes:
      - /srv/mysql:/var/lib/mysql
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'example'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
